config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :questions
  resources :answers
  resources :votes
  resources :comments
  root 'static_pages#home'
  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'questions' => 'questions#index'
  get 'new_questions' => 'questions#new'
  get 'question' => 'question#show'

  get 'upvote' => 'questions#upvote'
  get 'downvote' => 'questions#downvote'

  get 'update_answer' => 'answer#update'

  get 'new_comment' => 'comments#new'

end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :user
	has_many :answers
	has_many :votes, as: :votable
  has_many :comments, as: :commentable
	validates :title, :content, presence: true

  def add_user_vote(user)
    unless ( !!self.votes.find_by(user_id: user) == true )
      self.votes.create(user: user)
    else
      return false
    end
  end

  def total_answers
  	self.answers.size
  end

  def vote_count
  	size = self.votes.sum(:up) - self.votes.sum(:down)
  	size
  end

  def best_answer
    self.answers.find_by(best_answer: true)
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def new
		@question = Question.new
	end

	def create

		if session[:user_id].nil?
			redirect_to login_path
		else
		  @question = Question.new(question_params)
		  @user = User.find_by(id: session[:user_id])

			if @question.save
			  @user.questions << @question
			  redirect_to @question
			else 
			  flash[:danger] = "Oops...something's not right bout your question lad"
			  render 'new'
			end

		end
	end

	def upvote
	  if session[:user_id].nil?
	  	flash[:danger] = "You must login before you can vote"

	    redirect_to login_path
	  else
		@question = Question.find(session[:question_id])
		@user = User.find_by(id: session[:user_id])

		if @question.add_user_vote(@user)
          @question.votes.last.update(up: 1)
          flash[:success] = "You found this question useful, awesome!"

		  redirect_to @question
		else
		  flash[:danger] = "You've already voted!"

		  redirect_to @question
		end
	  end
	end

	def downvote
      if session[:user_id].nil?
	  	flash[:danger] = "You must login before you can vote"

	    redirect_to login_path
	  else
		@question = Question.find(session[:question_id])
		@user = User.find_by(id: session[:user_id])

		if @question.add_user_vote(@user)
          @question.votes.last.update(down: 1)
          flash[:success] = "Naw, maybe this question can be improved?"

		  redirect_to @question
	    else
	      flash[:danger] = "You've already voted!"

		  redirect_to @question
		end
	  end
	end

	def index
	  @questions = Question.all
	end

	def show
      @question = Question.find(params[:id])
      @no_best_answer = !@question.answers.find_by(best_answer:true)
      @question.views += 1
      @question.save!
      @best_answer = @question.best_answer
      session[:question_id] = params[:id]
      @user = @question.user
      @answer = Answer.new
      @comment = Comment.new
    end


private

    def question_params
      params.require(:question).permit(:title, :content)
    end

end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/questions/index.html.erb
<h1>Top Questions</h1>

<% unless @questions.nil? %>
  <table>
    <% @questions.each do |question|%>
      <tr>
      	<td>Votes: <%=question.votes.size%></td>
      	<td>Answers:<%=question.answers.size%></td>
        <td><%=link_to "#{question.title}", question%></td>
        <td>asked by <%=question.user.name%></td>
      </tr>
    <%end%>
</table>
<%end%>

app/views/questions/new.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@question) do |f| %>
		<%= f.label :title %>
		<%= f.text_field :title, class: 'form-control' %>
		<%= f.label :content %>
		<%= f.text_area :content, class: 'form-control' %>
		<%= f.submit "Submit question", class: "btn btn-primary" %>
		<% end %>

	</div>
</div>

app/views/questions/show.html.erb
<h1><%=@question.title%></h1>
<p>Asked by <%=@user.name%></p>
<%= link_to 'Vote Up', upvote_path %> |
<%= link_to 'Vote Down', downvote_path %>

<p><%=@question.content%></p>
<h4><%=@question.comments.size%> Comment(s)</h4>

<% @question.comments.each do |comment| %>
  <dt><%= comment.text %><dt>
  <dd>posted by <b><%= comment.user.name %></b><dd>
<% end %>

<div id="comment-form"></div>
<%= link_to "Add Comment", new_comment_path, remote: true %>
<h4><%=@question.total_answers%> Answer(s)</h4>

<% unless @question.answers.empty?%>
 
<table>
  <tr> 
    <% unless @best_answer.nil? %>
      <td><b>BEST ANSWER:</b> '<%= @best_answer.text %>'</td>
      <td>posted by <%= @best_answer.user.name %></td>
    <% end %>
  </tr>

  <tr>
    <% @question.answers.each do |posted_answer|%>
    <% next if posted_answer.best_answer %>
      <% if @user.id == session[:user_id] && @no_best_answer %>
        <%= form_for(posted_answer) do |f| %>
          <%= f.hidden_field :posted_answer_id, :value => posted_answer.id %>
          <td><%= f.submit 'Best Answer?', class: "btn" %></td>
        <% end %>
      <% end %>
      <td style="text-align:center;">'<%=posted_answer.text%>'</td>
      <td>posted by <%=posted_answer.user.name%></td>
  <tr>
    <% end %>
  </table>
<% end %>

<%= form_for(@answer) do |f| %>
 <div class="field">
    <b><%= f.label :text, "Your answer" %></b><br>
    <%= f.text_area :text %>
    <%= f.hidden_field :question_id, :value => @question.id %>
 </div>
 <div class="actions">
    <%= f.submit "Submit Answer", class: "btn btn-primary" %>
 </div>
<% end %>