config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :questions
  resources :answers
  resources :votes
  resources :comments
  root 'static_pages#home'
  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'questions' => 'questions#index'
  get 'new_questions' => 'questions#new'
  get 'question' => 'question#show'

  get 'upvote' => 'questions#upvote'
  get 'downvote' => 'questions#downvote'

  get 'update_answer' => 'answer#update'

  get 'new_comment' => 'comments#new'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :questions
	has_many :answers
	has_many :votes
	has_many :comments


	validates :password, length: {minimum: 6}
	before_save { self.email = email.downcase }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name, presence: true, length: {maximum: 50}
	validates :email, presence: true, length: {maximum: 255},
	                  format: { with: VALID_EMAIL_REGEX },
	                  uniqueness: { case_sensitive: false }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

	def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        log_in(@user)
        format.html { redirect_to @user, notice: flash[:success] = "Welcome, stay for awhile!" }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/user_helper.rb
module UserHelper

  def gravatar_for(user)
	gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
	gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
	image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  def log_in(user)
    session[:user_id] = user.id
  end
	
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
    <div class="field">
    <%= f.label :password_confirmation, "Confirm password" %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Create my account", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% provide(:title, @user.name)%>
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>
        </section>
    </aside>
</div>

<p>Got a question? <%= link_to 'Ask now!', new_question_path %></p>

<% unless @user.questions.nil? %>
<h2>Your recent questions</h2>
  <table>
  	<tr>
	<%@user.questions.each do |question|%>
  <td>Views: <%= question.views %></td>
  <td>Votes: <%= question.vote_count %></td>
  <td>Answers: <%= question.total_answers %></td>
	<td><%= link_to question.title , question_path(question) %><td>
	<tr>
 </table>
 <%end%>
 <%end%>