config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :questions
  resources :answers
  resources :votes
  resources :comments
  root 'static_pages#home'
  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'questions' => 'questions#index'
  get 'new_questions' => 'questions#new'
  get 'question' => 'question#show'

  get 'upvote' => 'questions#upvote'
  get 'downvote' => 'questions#downvote'

  get 'update_answer' => 'answer#update'

  get 'new_comment' => 'comments#new'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :user
	belongs_to :question
	has_many :votes, as: :votable
	has_many :comments, as: :commentable

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :commentable, polymorphic: true
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :user
	has_many :answers
	has_many :votes, as: :votable
  has_many :comments, as: :commentable
	validates :title, :content, presence: true

  def add_user_vote(user)
    unless ( !!self.votes.find_by(user_id: user) == true )
      self.votes.create(user: user)
    else
      return false
    end
  end

  def total_answers
  	self.answers.size
  end

  def vote_count
  	size = self.votes.sum(:up) - self.votes.sum(:down)
  	size
  end

  def best_answer
    self.answers.find_by(best_answer: true)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :questions
	has_many :answers
	has_many :votes
	has_many :comments


	validates :password, length: {minimum: 6}
	before_save { self.email = email.downcase }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name, presence: true, length: {maximum: 50}
	validates :email, presence: true, length: {maximum: 255},
	                  format: { with: VALID_EMAIL_REGEX },
	                  uniqueness: { case_sensitive: false }

end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :user
	belongs_to :votable, polymorphic: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

	def create
		@user = User.find(session[:user_id])
		@question = Question.find(params[:answer][:question_id])

		@question.answers.create(text: params[:answer][:text], user: @user)

		redirect_to @question
	end

	def update
	  @question = Question.find(session[:question_id])
	  answer = Answer.find(params[:answer][:posted_answer_id])
      answer.update(best_answer: true)

      redirect_to @question
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def new
	  @comment = Comment.new
	  @question = Question.find_by(id: session[:question_id])
	  respond_to do |format|
	  	format.html
	  	format.js
	  end
	end

	def show
	end

	def create
      if session[:user_id].nil?
			render 'login'
	    else
		  @question = Question.find_by(id: session[:question_id])
		  @user = User.find_by(id: session[:user_id])

		  respond_to do |format|
			if @question.comments.create(comment_params)
			   @question.comments.last.user = @user
	
			  format.html { redirect_to @question, notice: 'Woot, you posted a comment!' }
			  format.js
			else 
			  format.html {render :new}
			end
		  end
	    end
	end

	def edit
	end

	def update
	end

	def destroy
	end

	private

	def comment_params
		params.require(:comment).permit(:text, :commentable_type, :commentable_id, :user_id)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
	  user = User.find_by(email: params[:session][:email].downcase)

	  if user && user.authenticate(params[:session][:password])
	  	flash[:success] = "Welcome back 'ol chap"
		log_in(user)
		redirect_to(user)
	  end

	end

	def destroy
		log_out
		redirect_to root_url
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

	def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        log_in(@user)
        format.html { redirect_to @user, notice: flash[:success] = "Welcome, stay for awhile!" }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
end

app/helpers/answer_helper.rb
module AnswerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
      @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
      !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_controller_helper.rb
module UserControllerHelper
end

app/helpers/user_helper.rb
module UserHelper

  def gravatar_for(user)
	gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
	gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
	image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  def log_in(user)
    session[:user_id] = user.id
  end
	
end

app/helpers/vote_controller_helper.rb
module VoteControllerHelper
end

app/helpers/vote_helper.rb
module VoteHelper
end

app/views/layouts/_header.html.erb
<div class="container">
  <%= link_to "Thy Stack Overrunneth", root_path, id: "logo"%>
    <nav>
	  <ul class="nav navbar-nav navbar-right">
	  	<li><%= link_to "Latest Questions", questions_path %></li>
	    <li><%= link_to "Home", root_path %></li>
	    <% if logged_in? %>
	    <li><%= link_to "Log out", logout_path, method: "delete" %></li>
	    <li><%= link_to "My Account", user_path(session[:user_id])%></li>
	    <%else%>
		<li><%= link_to "Log in", login_path %></li>
		<li><%= link_to "Sign up", signup_path %></li>
		<%end%>
	  </ul>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thy Stack Overrunneth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <%= render 'layouts/header' %>
  </header>
  <% flash.each do |message_type,message|%>
  <div class="alert alert-<%= message_type %>"><%=message%></div>
  <%end%>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Thy Stack Overrunneth
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header.navbar.navbar-fixed-top.navbar-inverse
      = render 'layouts/header'
    - flash.each do |message_type,message|
      %div{:class => "alert alert-#{message_type}"}= message
    .container
      = yield